language: groovy
sudo: false
git:
  depth: 5
cache:
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
- openjdk6
deploy:
  - provider: script
    skip_cleanup: true
    script: "./gradlew publish"
    on:
      all_branches: true
      repo: ensime/ensime-gradle
      condition: "$TRAVIS_PULL_REQUEST != false"
      jdk: openjdk6
